---
name: 'Nitpick git commits'

on: [push]

jobs:
  nitpick:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Execute git linting
        uses: seravo/gitlint@v1.0.1
