---
name: 'Nitpick git commits'

on: [push]

env:
  DOMAINS: seravo.com
  PYTHON_VERSION: 3.8

jobs:
  nitpick:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}           
      
      - name: Install Gnitpick
        run: curl -O https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py

      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run gnitpick
        run: python3 gnitpick.py --verbose --email-domains "${DOMAINS}" --target-branch=main --main-branch=main