---
name: 'Lint PHP code'

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint-php-style:
    name: 'Lint style'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Setup repository
        uses: actions/checkout@v4

      # Install PHP and tools necessary
      - name: Setup PHP
        uses: seravo/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, composer

      # Print Composer version
      - run: composer --version

      # Install development dependencies
      - name: Install development dependencies
        run: composer install --no-interaction --no-progress

      # Print PHP_CodeSniffer version
      - run: vendor/bin/phpcs --version

      # Lint PHP code style
      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs -q
          --standard=PSR12
          --report=checkstyle src | cs2pr
